spring:
  profiles:
    active: dev
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    root: warn
    com.chadwick: trace
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
management:
  endpoints:
    jmx:
      exposure:
        include: health,metrics,info,env,beans,configprops
    web:
      exposure:
        include: health,info,metrics,env,beans,configprops
